from sqlalchemy.orm import Session
from . import models, schemas, auth

def create_todo(db: Session, todo: schemas.TodoCreate, user_id: int) -> models.Todo:
    #create a new_todo model instance
    new_todo = models.Todo(**todo.model_dump(), user_id=user_id)

    #stages the object for insertion without saving yet
    db.add(new_todo)

    #saves to the database
    db.commit()

    #refresh the object to load autogenerated fields
    db.refresh(new_todo)

    #return the the created object
    return new_todo

def get_todo(db: Session, todo_id: int) -> models.Todo | None:
    query = db.query(models.Todo)
    filtered_query = query.filter(models.Todo.id == todo_id).first()
    return filtered_query

def get_todos(db: Session, skip: int = 0, limit: int = 100) -> list[models.Todo]:
    query = db.query(models.Todo)
    get_offset = query.offset(skip).limit(limit).all()
    return get_offset

def update_todo(db: Session, todo_id: int, todo: schemas.TodoUpdate) -> models.Todo | None:
    # 1. Get the existing todo
    db_todo = get_todo(db, todo_id)
    if db_todo is None:
        return None

    # 2. Update the attributes on the existing object
    for key, value in todo.model_dump(exclude_unset=True).items():
        setattr(db_todo, key, value)

    # 3. Commit and refresh
    db.add(db_todo)
    db.commit()
    db.refresh(db_todo)
    return db_todo

def delete_todo(db: Session, todo_id: int) -> models.Todo | None:
    del_todo = get_todo(db, todo_id)
    if del_todo is None:
        return None

    db.delete(del_todo)
    db.commit()
    return del_todo

def create_user(db: Session, user: schemas.UserCreate) -> models.User:
    username = user.username
    email = user.email
    password = user.password

    db_user = models.User(
        username=username,
        email = email,
        hashed_password = auth.hash_password(password)
    )

    db.add(db_user)
    db.commit()
    db.refresh(db_user)
    return db_user

def get_user(db: Session, username: str) -> models.User:
    return db.query(models.User).filter(models.User.username == username).first()